{{ config(materialized='view') }}

SELECT 
    ip,
    city,
    region,
    country_short AS country_code,
    
    -- Map country name từ country_short (ĐẦY ĐỦ TẤT CẢ COUNTRIES)
    CASE country_short
        -- Europe
        WHEN 'AD' THEN 'Andorra'
        WHEN 'AL' THEN 'Albania'
        WHEN 'AT' THEN 'Austria'
        WHEN 'AX' THEN 'Åland Islands'
        WHEN 'BA' THEN 'Bosnia and Herzegovina'
        WHEN 'BE' THEN 'Belgium'
        WHEN 'BG' THEN 'Bulgaria'
        WHEN 'BY' THEN 'Belarus'
        WHEN 'CH' THEN 'Switzerland'
        WHEN 'CY' THEN 'Cyprus'
        WHEN 'CZ' THEN 'Czech Republic'
        WHEN 'DE' THEN 'Germany'
        WHEN 'DK' THEN 'Denmark'
        WHEN 'EE' THEN 'Estonia'
        WHEN 'ES' THEN 'Spain'
        WHEN 'FI' THEN 'Finland'
        WHEN 'FO' THEN 'Faroe Islands'
        WHEN 'FR' THEN 'France'
        WHEN 'GB' THEN 'United Kingdom'
        WHEN 'GG' THEN 'Guernsey'
        WHEN 'GI' THEN 'Gibraltar'
        WHEN 'GL' THEN 'Greenland'
        WHEN 'GR' THEN 'Greece'
        WHEN 'HR' THEN 'Croatia'
        WHEN 'HU' THEN 'Hungary'
        WHEN 'IE' THEN 'Ireland'
        WHEN 'IM' THEN 'Isle of Man'
        WHEN 'IS' THEN 'Iceland'
        WHEN 'IT' THEN 'Italy'
        WHEN 'JE' THEN 'Jersey'
        WHEN 'LI' THEN 'Liechtenstein'
        WHEN 'LT' THEN 'Lithuania'
        WHEN 'LU' THEN 'Luxembourg'
        WHEN 'LV' THEN 'Latvia'
        WHEN 'MC' THEN 'Monaco'
        WHEN 'MD' THEN 'Moldova'
        WHEN 'ME' THEN 'Montenegro'
        WHEN 'MK' THEN 'North Macedonia'
        WHEN 'MT' THEN 'Malta'
        WHEN 'NL' THEN 'Netherlands'
        WHEN 'NO' THEN 'Norway'
        WHEN 'PL' THEN 'Poland'
        WHEN 'PT' THEN 'Portugal'
        WHEN 'RO' THEN 'Romania'
        WHEN 'RS' THEN 'Serbia'
        WHEN 'RU' THEN 'Russia'
        WHEN 'SE' THEN 'Sweden'
        WHEN 'SI' THEN 'Slovenia'
        WHEN 'SK' THEN 'Slovakia'
        WHEN 'SM' THEN 'San Marino'
        WHEN 'UA' THEN 'Ukraine'
        WHEN 'VA' THEN 'Vatican City'
        
        -- North America
        WHEN 'AI' THEN 'Anguilla'
        WHEN 'AG' THEN 'Antigua and Barbuda'
        WHEN 'AW' THEN 'Aruba'
        WHEN 'BB' THEN 'Barbados'
        WHEN 'BM' THEN 'Bermuda'
        WHEN 'BQ' THEN 'Caribbean Netherlands'
        WHEN 'BS' THEN 'Bahamas'
        WHEN 'BZ' THEN 'Belize'
        WHEN 'CA' THEN 'Canada'
        WHEN 'CR' THEN 'Costa Rica'
        WHEN 'CU' THEN 'Cuba'
        WHEN 'CW' THEN 'Curaçao'
        WHEN 'DM' THEN 'Dominica'
        WHEN 'DO' THEN 'Dominican Republic'
        WHEN 'GD' THEN 'Grenada'
        WHEN 'GP' THEN 'Guadeloupe'
        WHEN 'GT' THEN 'Guatemala'
        WHEN 'HN' THEN 'Honduras'
        WHEN 'HT' THEN 'Haiti'
        WHEN 'JM' THEN 'Jamaica'
        WHEN 'KN' THEN 'Saint Kitts and Nevis'
        WHEN 'KY' THEN 'Cayman Islands'
        WHEN 'LC' THEN 'Saint Lucia'
        WHEN 'MF' THEN 'Saint Martin'
        WHEN 'MQ' THEN 'Martinique'
        WHEN 'MX' THEN 'Mexico'
        WHEN 'NI' THEN 'Nicaragua'
        WHEN 'PA' THEN 'Panama'
        WHEN 'PR' THEN 'Puerto Rico'
        WHEN 'SV' THEN 'El Salvador'
        WHEN 'SX' THEN 'Sint Maarten'
        WHEN 'TC' THEN 'Turks and Caicos Islands'
        WHEN 'TT' THEN 'Trinidad and Tobago'
        WHEN 'US' THEN 'United States'
        WHEN 'VC' THEN 'Saint Vincent and the Grenadines'
        WHEN 'VG' THEN 'British Virgin Islands'
        WHEN 'VI' THEN 'U.S. Virgin Islands'
        
        -- South America
        WHEN 'AR' THEN 'Argentina'
        WHEN 'BO' THEN 'Bolivia'
        WHEN 'BR' THEN 'Brazil'
        WHEN 'CL' THEN 'Chile'
        WHEN 'CO' THEN 'Colombia'
        WHEN 'EC' THEN 'Ecuador'
        WHEN 'GF' THEN 'French Guiana'
        WHEN 'GY' THEN 'Guyana'
        WHEN 'PE' THEN 'Peru'
        WHEN 'PY' THEN 'Paraguay'
        WHEN 'SR' THEN 'Suriname'
        WHEN 'UY' THEN 'Uruguay'
        WHEN 'VE' THEN 'Venezuela'
        
        -- Asia
        WHEN 'AE' THEN 'United Arab Emirates'
        WHEN 'AF' THEN 'Afghanistan'
        WHEN 'AM' THEN 'Armenia'
        WHEN 'AZ' THEN 'Azerbaijan'
        WHEN 'BD' THEN 'Bangladesh'
        WHEN 'BH' THEN 'Bahrain'
        WHEN 'BN' THEN 'Brunei'
        WHEN 'BT' THEN 'Bhutan'
        WHEN 'CN' THEN 'China'
        WHEN 'GE' THEN 'Georgia'
        WHEN 'HK' THEN 'Hong Kong'
        WHEN 'ID' THEN 'Indonesia'
        WHEN 'IL' THEN 'Israel'
        WHEN 'IN' THEN 'India'
        WHEN 'IQ' THEN 'Iraq'
        WHEN 'IR' THEN 'Iran'
        WHEN 'JO' THEN 'Jordan'
        WHEN 'JP' THEN 'Japan'
        WHEN 'KG' THEN 'Kyrgyzstan'
        WHEN 'KH' THEN 'Cambodia'
        WHEN 'KR' THEN 'South Korea'
        WHEN 'KW' THEN 'Kuwait'
        WHEN 'KZ' THEN 'Kazakhstan'
        WHEN 'LA' THEN 'Laos'
        WHEN 'LB' THEN 'Lebanon'
        WHEN 'LK' THEN 'Sri Lanka'
        WHEN 'MM' THEN 'Myanmar'
        WHEN 'MN' THEN 'Mongolia'
        WHEN 'MO' THEN 'Macau'
        WHEN 'MV' THEN 'Maldives'
        WHEN 'MY' THEN 'Malaysia'
        WHEN 'NP' THEN 'Nepal'
        WHEN 'OM' THEN 'Oman'
        WHEN 'PH' THEN 'Philippines'
        WHEN 'PK' THEN 'Pakistan'
        WHEN 'PS' THEN 'Palestine'
        WHEN 'QA' THEN 'Qatar'
        WHEN 'SA' THEN 'Saudi Arabia'
        WHEN 'SG' THEN 'Singapore'
        WHEN 'SY' THEN 'Syria'
        WHEN 'TH' THEN 'Thailand'
        WHEN 'TJ' THEN 'Tajikistan'
        WHEN 'TL' THEN 'Timor-Leste'
        WHEN 'TM' THEN 'Turkmenistan'
        WHEN 'TN' THEN 'Tunisia'
        WHEN 'TR' THEN 'Turkey'
        WHEN 'TW' THEN 'Taiwan'
        WHEN 'UZ' THEN 'Uzbekistan'
        WHEN 'VN' THEN 'Vietnam'
        WHEN 'YE' THEN 'Yemen'
        
        -- Oceania
        WHEN 'AU' THEN 'Australia'
        WHEN 'CK' THEN 'Cook Islands'
        WHEN 'FJ' THEN 'Fiji'
        WHEN 'GU' THEN 'Guam'
        WHEN 'NC' THEN 'New Caledonia'
        WHEN 'NR' THEN 'Nauru'
        WHEN 'NZ' THEN 'New Zealand'
        WHEN 'PF' THEN 'French Polynesia'
        WHEN 'PG' THEN 'Papua New Guinea'
        WHEN 'SB' THEN 'Solomon Islands'
        WHEN 'TO' THEN 'Tonga'
        WHEN 'VU' THEN 'Vanuatu'
        WHEN 'WF' THEN 'Wallis and Futuna'
        WHEN 'WS' THEN 'Samoa'
        
        -- Africa
        WHEN 'AO' THEN 'Angola'
        WHEN 'BF' THEN 'Burkina Faso'
        WHEN 'BI' THEN 'Burundi'
        WHEN 'BJ' THEN 'Benin'
        WHEN 'BW' THEN 'Botswana'
        WHEN 'CD' THEN 'Democratic Republic of the Congo'
        WHEN 'CF' THEN 'Central African Republic'
        WHEN 'CG' THEN 'Republic of the Congo'
        WHEN 'CI' THEN 'Côte d\'Ivoire'
        WHEN 'CM' THEN 'Cameroon'
        WHEN 'CV' THEN 'Cape Verde'
        WHEN 'DJ' THEN 'Djibouti'
        WHEN 'DZ' THEN 'Algeria'
        WHEN 'EG' THEN 'Egypt'
        WHEN 'ET' THEN 'Ethiopia'
        WHEN 'GA' THEN 'Gabon'
        WHEN 'GH' THEN 'Ghana'
        WHEN 'GM' THEN 'Gambia'
        WHEN 'GN' THEN 'Guinea'
        WHEN 'GQ' THEN 'Equatorial Guinea'
        WHEN 'GW' THEN 'Guinea-Bissau'
        WHEN 'KE' THEN 'Kenya'
        WHEN 'KM' THEN 'Comoros'
        WHEN 'LR' THEN 'Liberia'
        WHEN 'LS' THEN 'Lesotho'
        WHEN 'LY' THEN 'Libya'
        WHEN 'MA' THEN 'Morocco'
        WHEN 'MG' THEN 'Madagascar'
        WHEN 'ML' THEN 'Mali'
        WHEN 'MR' THEN 'Mauritania'
        WHEN 'MU' THEN 'Mauritius'
        WHEN 'MW' THEN 'Malawi'
        WHEN 'MZ' THEN 'Mozambique'
        WHEN 'NA' THEN 'Namibia'
        WHEN 'NE' THEN 'Niger'
        WHEN 'NG' THEN 'Nigeria'
        WHEN 'RE' THEN 'Réunion'
        WHEN 'RW' THEN 'Rwanda'
        WHEN 'SC' THEN 'Seychelles'
        WHEN 'SD' THEN 'Sudan'
        WHEN 'SL' THEN 'Sierra Leone'
        WHEN 'SN' THEN 'Senegal'
        WHEN 'SO' THEN 'Somalia'
        WHEN 'ST' THEN 'São Tomé and Príncipe'
        WHEN 'SZ' THEN 'Eswatini'
        WHEN 'TD' THEN 'Chad'
        WHEN 'TG' THEN 'Togo'
        WHEN 'TZ' THEN 'Tanzania'
        WHEN 'UG' THEN 'Uganda'
        WHEN 'YT' THEN 'Mayotte'
        WHEN 'ZA' THEN 'South Africa'
        WHEN 'ZM' THEN 'Zambia'
        WHEN 'ZW' THEN 'Zimbabwe'
        
        -- Special cases
        WHEN '-' THEN 'Unknown'
        WHEN 'IPV6 ADDRESS MISSING IN IPV4 BIN' THEN 'Unknown'
        WHEN 'INVALID IP ADDRESS' THEN 'Unknown'
        
        ELSE country_short
    END AS country_name,
    
    

FROM {{ source('test', 'ip_locations') }}
WHERE ip IS NOT NULL
    AND country_short NOT IN ('-', 'IPV6 ADDRESS MISSING IN IPV4 BIN', 'INVALID IP ADDRESS')